#!/usr/bin/env python3
"""Generate deterministic Markdown command references from a merged tree."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

HEADER = "<!-- Generated by scripts/generate_references.py. Do not edit. -->"


def escape(value: Any) -> str:
    text = str(value).replace("\n", " ").replace("|", "\\|")
    return re.sub(r"\s+", " ", text).strip()


def code(value: Any) -> str:
    return f"`{str(value).replace('`', '\\`')}`"


def platform_list(command: dict[str, Any]) -> str:
    return (
        ", ".join(platform for platform, available in command["availability"].items() if available)
        or "None"
    )


def _table(headers: list[str], rows: list[list[str]]) -> list[str]:
    if not rows:
        return ["None."]
    return [
        f"| {' | '.join(headers)} |",
        f"| {' | '.join('---' for _ in headers)} |",
        *(f"| {' | '.join(row)} |" for row in rows),
    ]


def _render_command(command: dict[str, Any], cli_version: str) -> list[str]:
    path = " ".join(["unity", *command["path"]])
    lines = [
        f"## {path}",
        "",
        f"- CLI version: {code(cli_version)}",
        f"- Supported platforms: {platform_list(command)}",
        f"- Aliases: {', '.join(code(alias) for alias in command['aliases']) or 'None'}",
        "",
        command["summary"] or "No summary exposed by help.",
    ]
    if command["description"]:
        lines.extend(["", command["description"]])
    for label, notices in (
        ("Experimental", command["experimental_notices"]),
        ("Deprecated", command["deprecation_notices"]),
        ("Platform restrictions", command["platform_restrictions"]),
    ):
        if notices:
            lines.extend(["", f"**{label}:** " + " ".join(escape(item) for item in notices)])

    lines.extend(["", "### Usage", ""])
    lines.extend([code(item) for item in command["usage"]] or ["No usage signature exposed."])
    lines.extend(["", "### Subcommands", ""])
    lines.extend(
        _table(
            ["Name", "Aliases", "Summary"],
            [
                [
                    code(item["name"]),
                    ", ".join(code(alias) for alias in item["aliases"]) or "—",
                    escape(item["summary"]),
                ]
                for item in command["subcommands"]
                if item["name"] != "help"
            ],
        )
    )
    lines.extend(["", "### Positional arguments", ""])
    lines.extend(
        _table(
            ["Argument", "Required", "Repeatable", "Description"],
            [
                [
                    code(item["name"]),
                    str(item["required"]),
                    str(item["repeatable"]),
                    escape(item["description"]),
                ]
                for item in command["arguments"]
            ],
        )
    )
    lines.extend(["", "### Options", ""])
    lines.extend(
        _table(
            ["Option", "Value", "Required", "Repeatable", "Default", "Description"],
            [
                [
                    ", ".join(code(name) for name in item["names"]),
                    code(item["value"]) if item["value"] else "—",
                    str(item["required"]),
                    str(item["repeatable"]),
                    code(item["default"]) if item["default"] is not None else "—",
                    escape(item["description"]),
                ]
                for item in command["options"]
            ],
        )
    )
    lines.extend(["", "### Environment variables", ""])
    lines.extend(
        _table(
            ["Variable", "Description"],
            [
                [code(item["name"]), escape(item["description"])]
                for item in command["environment_variables"]
            ],
        )
    )
    lines.extend(["", "### Examples exposed by help", ""])
    lines.extend([code(item) for item in command["examples"]] or ["None."])
    lines.extend(["", "### Exit codes", ""])
    lines.extend(
        _table(
            ["Code", "Meaning"],
            [[code(item["code"]), escape(item["description"])] for item in command["exit_codes"]],
        )
    )
    if command["extra_sections"]:
        lines.extend(["", "### Additional help sections", ""])
        for section in command["extra_sections"]:
            lines.extend(
                [
                    f"#### {escape(section['heading'])}",
                    "",
                    "```text",
                    *section["lines"],
                    "```",
                    "",
                ]
            )
    if command["platform_overrides"]:
        lines.extend(["", "### Platform-specific differences", ""])
        for platform, fields in sorted(command["platform_overrides"].items()):
            lines.append(f"- **{platform}:** differs in {', '.join(sorted(fields))}.")
    lines.extend(
        [
            "",
            f"Confirm behavior with `{path} --help` on the target machine before execution.",
            "",
        ]
    )
    return lines


def render_index(tree: dict[str, Any]) -> str:
    top_level = [command for command in tree["commands"] if len(command["path"]) == 1]
    lines = [
        HEADER,
        "",
        "# Unity CLI command index",
        "",
        f"Generated from Unity CLI {code(tree['cli_version'])} help output.",
        "",
        "Installed help remains authoritative. Run `unity --help` and the complete command "
        "path with `--help` before use.",
        "",
        "| Command | Aliases | Platforms | Summary |",
        "| --- | --- | --- | --- |",
    ]
    for command in top_level:
        slug = command["path"][0]
        lines.append(
            f"| [{code(slug)}](command-{slug}.md) | "
            f"{', '.join(code(alias) for alias in command['aliases']) or '—'} | "
            f"{platform_list(command)} | {escape(command['summary'])} |"
        )
    return "\n".join(lines) + "\n"


def render_top_level(tree: dict[str, Any], top_level: str) -> str:
    commands = [
        command
        for command in tree["commands"]
        if command["path"] and command["path"][0] == top_level
    ]
    lines = [
        HEADER,
        "",
        f"# `unity {top_level}` command reference",
        "",
        f"Generated from Unity CLI {code(tree['cli_version'])} help output.",
        "",
        "Installed help is authoritative; this file is a versioned snapshot.",
        "",
    ]
    for command in commands:
        lines.extend(_render_command(command, tree["cli_version"]))
    return "\n".join(lines).rstrip() + "\n"


def generated_files(tree: dict[str, Any]) -> dict[str, str]:
    top_levels = sorted({command["path"][0] for command in tree["commands"] if command["path"]})
    return {
        "command-index.md": render_index(tree),
        **{f"command-{name}.md": render_top_level(tree, name) for name in top_levels},
    }


def generate(tree: dict[str, Any], output_directory: Path) -> None:
    output_directory.mkdir(parents=True, exist_ok=True)
    expected = generated_files(tree)
    for stale in output_directory.glob("command-*.md"):
        if stale.name not in expected:
            stale.unlink()
    for name, content in expected.items():
        (output_directory / name).write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tree", type=Path)
    parser.add_argument("--output", type=Path, default=Path("references"))
    args = parser.parse_args()
    generate(json.loads(args.tree.read_text(encoding="utf-8")), args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
